name: Publish
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# on: [push]
# on:
#   push:
#     branches:
#       - main

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_TEST_CD }}
      
      - name: Build image
        run: |
          docker build . --tag ghcr.io/jfloresq1987/video-generator-back:latest
          docker push ghcr.io/jfloresq1987/video-generator-back:latest

  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest
    env:
      PORT: 4242
      STRIPE_PRIVATE_KEY: ${{ secrets.STRIPE_PRIVATE_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      WEBHOOK_END_POINT_SECRET: ${{ secrets.WEBHOOK_END_POINT_SECRET }}
      WEB_URL: http://localhost:4200/sales
    steps:
      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: SSH into Server
        run: |
          sshpass -p '${{ secrets.AUTH_PASS }}' ssh -o StrictHostKeyChecking=no ${{ secrets.AUTH_SERVER }} << EOF
            cd /var/www/video-generator-back/
            docker login ghcr.io -u jfloresq1987 -p ${{ secrets.TOKEN_TEST_CD }}
            docker pull ghcr.io/jfloresq1987/video-generator-back:latest
            docker stop video-generator-back && docker rm video-generator-back
            docker run -d \
              --name video-generator-back \
              -p 80:4242 \
              -v ./app:/app \
              -w /app \
              --restart always \
              ghcr.io/jfloresq1987/video-generator-back:latest
          EOF
